# Generated by Django 5.2 on 2025-11-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_reactions_comment_user_reactions'),
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='comments.comment'),
        ),
    ]
