# Generated by Django 5.2 on 2025-11-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_audio_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
