# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 5.2.6.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# from datetime import timedelta
# import os
# from dotenv import load_dotenv
# load_dotenv()
# from corsheaders.defaults import default_headers
# import logging
# from decouple import config
# from corsheaders.defaults import default_headers

# # Load environment variables
# load_dotenv()


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!

# # SECRET_KEY = os.getenv('SECRET_KEY')
# # SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-gzj350!03v(a7d(lmcj3@!ra93fvdx$x4tr0zz_o0s^ejp!s+k")  # Updated to use env, with fallback
# SECRET_KEY = os.getenv('SECRET_KEY')  # Updated to use env, with fallback
# DEBUG = os.getenv('DEBUG', 'False') == 'True'
# # DEBUG = True

# # SECURITY WARNING: don't run with debug turned on in production!

# # Add to settings.py (assuming it's not there)
# PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")
# PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
# # Application definition
# if not PAYSTACK_SECRET_KEY or not PAYSTACK_PUBLIC_KEY:
#     raise ValueError("PAYSTACK_SECRET_KEY and PAYSTACK_PUBLIC_KEY must be set in the .env file")

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'cloudinary_storage',  # Added for Cloudinary media storage
#     'cloudinary',  # Added for Cloudinary SDK
#     'rest_framework',
#     'corsheaders',
#     'rest_framework_simplejwt',
#     'rest_framework_simplejwt.token_blacklist',
#     'accounts',
#     'userprofile',
#     'publications',
#     'payments',
#     'messagebox',
#     'comments',
#     'points',
#     'rewardcode',
#     'tasks',
#     'emoji',
#     'conference',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     # "middleware.disable_csrf.DisableCSRF",
#     'whitenoise.middleware.WhiteNoiseMiddleware',  # keep here
#     'corsheaders.middleware.CorsMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]


# ALLOWED_HOSTS = [
#     'panel-ayrn.onrender.com',
#     'scholar-panel.vercel.app',
#     'localhost',
#     '127.0.0.1',
# ]

# CSRF_TRUSTED_ORIGINS = [
#     'https://panel-ayrn.onrender.com',
#     'https://scholar-panel.vercel.app',
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
#     'http://localhost:3001',
# ]

# # ✅ Allow frontend to make API calls
# CORS_ALLOWED_ORIGINS = [
#     'https://scholar-panel.vercel.app',
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
#     'http://localhost:3001',
# ]



# ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# AUTH_USER_MODEL = "accounts.User"

# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),   # or minutes=15
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
#     "ROTATE_REFRESH_TOKENS": True,
#     "BLACKLIST_AFTER_ROTATION": True,
# }

# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = list(default_headers) + [
#     "Cookie",
# ]
# # SECURE_SSL_REDIRECT = True
# SECURE_SSL_REDIRECT = False
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'accounts.authentication.CookieJWTAuthentication',
#         # 'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
#     "PAGE_SIZE": 10,
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     ),  # Enforce JSON responses
#     'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
#     'DEFAULT_THROTTLE_CLASSES': [
#     'rest_framework.throttling.AnonRateThrottle',
#     'rest_framework.throttling.UserRateThrottle'
#   ],
    
#   'DEFAULT_THROTTLE_RATES': {
#     'anon': '2/minute',
#     'user': '100/minute',
#     'verify-passcode': '2/minute',
#     'polling': '100/minute',
#   },
  
#    "DEFAULT_PARSER_CLASSES": [
#         "rest_framework.parsers.JSONParser",
#         "rest_framework.parsers.FormParser",
#         "rest_framework.parsers.MultiPartParser",
#     ],
  
# }


    


# WSGI_APPLICATION = 'config.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Africa/Lagos'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # Media files (uploads)
# MEDIA_URL = 'api/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Comment this out in production: # MEDIA_ROOT = ...


# # Added: Cloudinary configuration
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
#     'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
#     'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
#     'SECURE': True,  # Enforces HTTPS for production security
# }
# # Logging configuration
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

# # Optional: If most uploads are images, set this default (override per-field for videos/raw as needed)
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

# try:
#     from .deployment_settings import *
# except ImportError:
#     pass
















# # """
# # Django settings for config project.

# # Generated by 'django-admin startproject' using Django 5.2.6.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/5.2/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/5.2/ref/settings/
# # """

# # from pathlib import Path
# # from datetime import timedelta
# # import os
# # from dotenv import load_dotenv
# # load_dotenv()
# # from corsheaders.defaults import default_headers
# # import logging
# # from decouple import config

# # # Load environment variables
# # load_dotenv()


# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!

# # # SECRET_KEY = os.getenv('SECRET_KEY')
# # # SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-gzj350!03v(a7d(lmcj3@!ra93fvdx$x4tr0zz_o0s^ejp!s+k")  # Updated to use env, with fallback
# # SECRET_KEY = os.getenv('SECRET_KEY')  # Updated to use env, with fallback
# # DEBUG = os.getenv('DEBUG', 'False') == 'True'
# # # DEBUG = True

# # # SECURITY WARNING: don't run with debug turned on in production!

# # # Add to settings.py (assuming it's not there)
# # PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")
# # PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
# # # Application definition
# # if not PAYSTACK_SECRET_KEY or not PAYSTACK_PUBLIC_KEY:
# #     raise ValueError("PAYSTACK_SECRET_KEY and PAYSTACK_PUBLIC_KEY must be set in the .env file")

# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'cloudinary_storage',  # Added for Cloudinary media storage
# #     'cloudinary',  # Added for Cloudinary SDK
# #     'rest_framework',
# #     'corsheaders',
# #     'rest_framework_simplejwt',
# #     'rest_framework_simplejwt.token_blacklist',
# #     'accounts',
# #     'userprofile',
# #     'publications',
# #     'payments',
# #     'messagebox',
# #     'comments',
# #     'points',
# #     'rewardcode',
# # ]

# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'whitenoise.middleware.WhiteNoiseMiddleware',  # keep here
# #     'corsheaders.middleware.CorsMiddleware',        # move up here
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]


# # ALLOWED_HOSTS = [
# #     'panel-ayrn.onrender.com',
# #     'scholar-panel.vercel.app',
# #     'localhost',
# #     '127.0.0.1',
# # ]

# # CSRF_TRUSTED_ORIGINS = [
# #     'https://panel-ayrn.onrender.com',
# #     'https://scholar-panel.vercel.app',
# #     'http://localhost:3000',
# #     'http://127.0.0.1:3000',
# # ]

# # # ✅ Allow frontend to make API calls
# # CORS_ALLOWED_ORIGINS = [
# #     'https://scholar-panel.vercel.app',
# #     'http://localhost:3000',
# #     'http://127.0.0.1:3000',
# #     'http://localhost:3001',
# # ]



# # ROOT_URLCONF = 'config.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # AUTH_USER_MODEL = "accounts.User"

# # SIMPLE_JWT = {
# #     "ACCESS_TOKEN_LIFETIME": timedelta(days=3),
# #     "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
# #     "ROTATE_REFRESH_TOKENS": True,
# #     "BLACKLIST_AFTER_ROTATION": True,
# # }

# # REST_FRAMEWORK = {
# #     'DEFAULT_AUTHENTICATION_CLASSES': (
# #         'rest_framework_simplejwt.authentication.JWTAuthentication',
# #     ),
# #     "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
# #     "PAGE_SIZE": 10,
# #     'DEFAULT_RENDERER_CLASSES': (
# #         'rest_framework.renderers.JSONRenderer',
# #     ),  # Enforce JSON responses
# #     'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
# #     'DEFAULT_THROTTLE_CLASSES': [
# #     'rest_framework.throttling.AnonRateThrottle',
# #     'rest_framework.throttling.UserRateThrottle'
# #   ],
# #   'DEFAULT_THROTTLE_RATES': {
# #     'anon': '2/minute',
# #     'user': '100/minute',
# #     'verify-passcode': '2/minute',
# #     'polling': '100/minute',
# #   }
  
# # }


    


# # WSGI_APPLICATION = 'config.wsgi.application'


# # # Database
# # # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # # Password validation
# # # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/5.2/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'Africa/Lagos'

# # USE_I18N = True

# # USE_TZ = True


# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/5.2/howto/static-files/

# # STATIC_URL = '/static/'
# # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# # # Default primary key field type
# # # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # # Media files (uploads)
# # MEDIA_URL = 'api/media/'
# # MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Comment this out in production: # MEDIA_ROOT = ...


# # # Added: Cloudinary configuration
# # CLOUDINARY_STORAGE = {
# #     'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
# #     'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
# #     'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
# #     'SECURE': True,  # Enforces HTTPS for production security
# # }
# # # Logging configuration
# # LOGGING = {
# #     'version': 1,
# #     'disable_existing_loggers': False,
# #     'handlers': {
# #         'console': {
# #             'class': 'logging.StreamHandler',
# #         },
# #     },
# #     'loggers': {
# #         '': {
# #             'handlers': ['console'],
# #             'level': 'DEBUG',
# #             'propagate': True,
# #         },
# #     },
# # }

# # # Optional: If most uploads are images, set this default (override per-field for videos/raw as needed)
# # DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# # PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

# # try:
# #     from .deployment_settings import *
# # except ImportError:
# #     pass










from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from decouple import config
import dj_database_url

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"

PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")
PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")

if not PAYSTACK_SECRET_KEY or not PAYSTACK_PUBLIC_KEY:
    raise ValueError("PAYSTACK keys missing in .env")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'cloudinary_storage',
    'cloudinary',

    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'accounts',
    'userprofile',
    'publications',
    'payments',
    'messagebox',
    'comments',
    'points',
    'rewardcode',
    'tasks',
    'emoji',
    'conference',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',


    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ALLOWED_HOSTS = [
    "panel-1-tlqv.onrender.com",
    "scholar-panel.vercel.app",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://panel-1-tlqv.onrender.com",
    "https://scholar-panel.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGINS = [
    "https://scholar-panel.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
]


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["Cookie"]
CORS_EXPOSE_HEADERS = ["Set-Cookie"]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_DOMAIN = ".scholar-panel.vercel.app"
CSRF_COOKIE_DOMAIN = ".scholar-panel.vercel.app"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

X_FRAME_OPTIONS = "DENY"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "accounts.User"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
}

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "api/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
    "SECURE": True,
}

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")

try:
    from .deployment_settings import *
except ImportError:
    pass
