# Generated by Django 5.2 on 2025-10-22 19:50

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
import publications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book/Book Chapter'), ('thesis', 'Thesis/Dissertation'), ('report', 'Technical Report'), ('review', 'Review Paper'), ('case_study', 'Case Study'), ('editorial', 'Editorial/Opinion'), ('news', 'News/Blog'), ('other', 'Other')], max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'indexes': [models.Index(fields=['name'], name='publication_name_ca3a81_idx')],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.CharField(default=publications.models.generate_short_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('is_free_review', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='publications/')),
                ('video_file', models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated list of keywords (e.g., machine learning, AI)')),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('rejection_count', models.PositiveIntegerField(default=0)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.category')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='publications.publication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_liked', models.BooleanField(default=False)),
                ('user_disliked', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to='publications.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['author', 'publication_date'], name='publication_author__84c8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['title', 'abstract', 'keywords'], name='search_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status'], name='publication_status_40d0d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('publication', 'user')},
        ),
    ]
