# Generated by Django 5.2 on 2025-11-03 01:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='annotated_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='annotations/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='editor_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
