# Generated by Django 5.2 on 2025-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_annotated_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
