# Generated by Django 5.2 on 2025-11-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
