# Generated by Django 5.2 on 2025-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
