# Generated by Django 5.2 on 2025-11-26 19:09

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_delete_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='co_authored_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Featured image (16:9 recommended)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='license',
            field=models.CharField(choices=[('cc-by', 'CC BY 4.0'), ('cc-by-sa', 'CC BY-SA 4.0'), ('cc-by-nc', 'CC BY-NC 4.0')], default='cc-by', max_length=50),
        ),
        migrations.AddField(
            model_name='views',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
