# Generated by Django 5.2 on 2025-11-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_co_authors_publication_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='license',
        ),
    ]
