# Generated by Django 5.2 on 2025-11-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_remove_publication_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='co_authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='co_author_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
