# Generated by Django 5.2 on 2025-11-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_task',
        ),
    ]
