# Generated by Django 5.2 on 2025-11-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_remove_notification_notification_type_and_more'),
        ('tasks', '0002_alter_task_options_alter_task_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
