# Generated by Django 5.2 on 2025-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_notification_related_task_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('publication', 'Publication'), ('message', 'Message'), ('comment', 'Comment')], max_length=20),
        ),
    ]
