# Generated by Django 5.2 on 2025-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
